// <auto-generated />
using System;
using DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DataAccess.Migrations
{
    [DbContext(typeof(VotingRegisterContext))]
    [Migration("20190619114832_AutoIncrementOnIds")]
    partial class AutoIncrementOnIds
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("DataAccess.Aspnetroleclaims", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int(11)");

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .IsUnicode(false);

                    b.HasKey("Id");

                    b.HasIndex("RoleId")
                        .HasName("IX_AspNetRoleClaims_RoleId");

                    b.ToTable("aspnetroleclaims","votingregister");
                });

            modelBuilder.Entity("DataAccess.Aspnetroles", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(128)
                        .IsUnicode(false);

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("longtext");

                    b.Property<string>("Discriminator")
                        .HasMaxLength(128)
                        .IsUnicode(false);

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .IsUnicode(false);

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(128)
                        .IsUnicode(false);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex");

                    b.ToTable("aspnetroles","votingregister");
                });

            modelBuilder.Entity("DataAccess.Aspnetuserclaims", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int(11)");

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .IsUnicode(false);

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .HasName("IX_AspNetUserClaims_UserId");

                    b.ToTable("aspnetuserclaims","votingregister");
                });

            modelBuilder.Entity("DataAccess.Aspnetuserlogins", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .IsUnicode(false);

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .IsUnicode(false);

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .IsUnicode(false);

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId")
                        .HasName("IX_AspNetUserLogins_UserId");

                    b.ToTable("aspnetuserlogins","votingregister");
                });

            modelBuilder.Entity("DataAccess.Aspnetuserroles", b =>
                {
                    b.Property<string>("UserId")
                        .HasMaxLength(128)
                        .IsUnicode(false);

                    b.Property<string>("RoleId")
                        .HasMaxLength(128)
                        .IsUnicode(false);

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId")
                        .HasName("IX_AspNetUserRoles_RoleId");

                    b.ToTable("aspnetuserroles","votingregister");
                });

            modelBuilder.Entity("DataAccess.Aspnetusers", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(128)
                        .IsUnicode(false);

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int(11)");

                    b.Property<string>("AdministrativeRajon")
                        .HasColumnName("Administrative_Rajon")
                        .HasMaxLength(2)
                        .IsUnicode(false);

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("longtext");

                    b.Property<string>("Discriminator")
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .IsUnicode(false);

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit(1)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit(1)");

                    b.Property<DateTime?>("LockoutEnd")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Names")
                        .IsRequired()
                        .HasMaxLength(128)
                        .IsUnicode(false);

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .IsUnicode(false);

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(128)
                        .IsUnicode(false);

                    b.Property<int?>("OtPartiq")
                        .HasColumnName("Ot_Partiq")
                        .HasColumnType("int(5)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("longtext");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit(1)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("longtext");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit(1)");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .IsUnicode(false);

                    b.HasKey("Id");

                    b.HasIndex("AdministrativeRajon")
                        .HasName("FK_aspnetusers_wntoa_RajonNkod");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex");

                    b.HasIndex("OtPartiq")
                        .HasName("FK_aspnetusers_sila_PartiqIdParty");

                    b.ToTable("aspnetusers","votingregister");
                });

            modelBuilder.Entity("DataAccess.Aspnetusertokens", b =>
                {
                    b.Property<string>("UserId")
                        .HasMaxLength(128)
                        .IsUnicode(false);

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .IsUnicode(false);

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .IsUnicode(false);

                    b.Property<string>("Value")
                        .HasColumnType("longtext");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("aspnetusertokens","votingregister");
                });

            modelBuilder.Entity("DataAccess.IdReturnSet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.HasKey("Id");

                    b.ToTable("IdReturnSet");
                });

            modelBuilder.Entity("DataAccess.NLica", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID")
                        .HasColumnType("int(7)");

                    b.Property<string>("Ap")
                        .HasColumnName("AP")
                        .HasMaxLength(3)
                        .IsUnicode(false);

                    b.Property<string>("Blok")
                        .HasColumnName("BLOK")
                        .HasMaxLength(5)
                        .IsUnicode(false);

                    b.Property<string>("Egn")
                        .IsRequired()
                        .HasColumnName("EGN")
                        .HasMaxLength(128)
                        .IsUnicode(false);

                    b.Property<string>("Et")
                        .HasColumnName("ET")
                        .HasMaxLength(2)
                        .IsUnicode(false);

                    b.Property<string>("Im1")
                        .HasColumnName("IM1")
                        .HasMaxLength(128)
                        .IsUnicode(false);

                    b.Property<string>("Im2")
                        .HasColumnName("IM2")
                        .HasMaxLength(128)
                        .IsUnicode(false);

                    b.Property<string>("Im3")
                        .HasColumnName("IM3")
                        .HasMaxLength(128)
                        .IsUnicode(false);

                    b.Property<string>("Impmessage")
                        .HasColumnName("impmessage")
                        .HasMaxLength(100)
                        .IsUnicode(false);

                    b.Property<int?>("Impstatus")
                        .HasColumnName("impstatus")
                        .HasColumnType("int(11)");

                    b.Property<string>("JkKv")
                        .HasColumnName("JK_KV")
                        .HasMaxLength(2)
                        .IsUnicode(false);

                    b.Property<DateTime?>("Koga")
                        .HasColumnName("KOGA");

                    b.Property<string>("Nas")
                        .HasColumnName("NAS")
                        .HasMaxLength(5)
                        .IsUnicode(false);

                    b.Property<string>("Naz")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("NAZ")
                        .HasDefaultValueSql("BG")
                        .HasMaxLength(2)
                        .IsUnicode(false);

                    b.Property<string>("Nom")
                        .HasColumnName("NOM")
                        .HasMaxLength(6)
                        .IsUnicode(false);

                    b.Property<string>("Obl")
                        .HasColumnName("OBL")
                        .HasMaxLength(3)
                        .IsUnicode(false);

                    b.Property<string>("Obra")
                        .HasMaxLength(16)
                        .IsUnicode(false);

                    b.Property<string>("Obs")
                        .HasColumnName("OBS")
                        .HasMaxLength(5)
                        .IsUnicode(false);

                    b.Property<string>("Pas1")
                        .HasColumnName("PAS1")
                        .HasMaxLength(1)
                        .IsUnicode(false);

                    b.Property<string>("Pas2")
                        .HasColumnName("PAS2")
                        .HasMaxLength(10)
                        .IsUnicode(false);

                    b.Property<DateTime?>("Pas3")
                        .HasColumnName("PAS3");

                    b.Property<string>("Pas4")
                        .HasColumnName("PAS4")
                        .HasMaxLength(2)
                        .IsUnicode(false);

                    b.Property<string>("Pk")
                        .HasColumnName("PK")
                        .HasMaxLength(4)
                        .IsUnicode(false);

                    b.Property<string>("Raj")
                        .HasColumnName("RAJ")
                        .HasMaxLength(2)
                        .IsUnicode(false);

                    b.Property<string>("SpeС")
                        .HasMaxLength(16)
                        .IsUnicode(false);

                    b.Property<string>("Tel")
                        .HasColumnName("TEL")
                        .HasMaxLength(14)
                        .IsUnicode(false);

                    b.Property<string>("Ul")
                        .HasColumnName("UL")
                        .HasMaxLength(5)
                        .IsUnicode(false);

                    b.Property<string>("User")
                        .HasColumnName("USER")
                        .HasMaxLength(128)
                        .IsUnicode(false);

                    b.Property<string>("Vh")
                        .HasColumnName("VH")
                        .HasMaxLength(2)
                        .IsUnicode(false);

                    b.Property<int?>("VidId")
                        .HasColumnName("Vid_id")
                        .HasColumnType("int(1)");

                    b.HasKey("Id");

                    b.HasIndex("JkKv")
                        .HasName("JK_KV");

                    b.HasIndex("Nas")
                        .HasName("NAS");

                    b.HasIndex("Obl")
                        .HasName("OBL");

                    b.HasIndex("Obs")
                        .HasName("OBS");

                    b.HasIndex("Raj")
                        .HasName("RAJ");

                    b.HasIndex("Ul")
                        .HasName("UL");

                    b.ToTable("n_lica","votingregister");
                });

            modelBuilder.Entity("DataAccess.NLicaDopylnenie", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnName("ID")
                        .HasColumnType("int(7)");

                    b.Property<string>("CodeOperacia")
                        .HasColumnName("Code_operacia")
                        .HasMaxLength(3)
                        .IsUnicode(false);

                    b.Property<int?>("IdLice")
                        .HasColumnName("Id_Lice")
                        .HasColumnType("int(7)");

                    b.Property<DateTime?>("Koga");

                    b.Property<int?>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(1)")
                        .HasDefaultValueSql("1");

                    b.Property<string>("User")
                        .HasMaxLength(128)
                        .IsUnicode(false);

                    b.Property<string>("VidCodeT")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Vid_codeT")
                        .HasColumnType("char(1)")
                        .HasDefaultValueSql("3");

                    b.HasKey("Id");

                    b.HasIndex("IdLice")
                        .HasName("FK_nlicadop_nlica");

                    b.ToTable("n_lica_dopylnenie","votingregister");
                });

            modelBuilder.Entity("DataAccess.NLicaImport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("int(11)");

                    b.Property<string>("Egn")
                        .IsRequired()
                        .HasColumnName("egn")
                        .HasMaxLength(10)
                        .IsUnicode(false);

                    b.Property<string>("Im1")
                        .IsRequired()
                        .HasColumnName("im1")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<string>("Im2")
                        .IsRequired()
                        .HasColumnName("im2")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<string>("Im3")
                        .IsRequired()
                        .HasColumnName("im3")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<string>("Obra")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<string>("Opisanie")
                        .HasColumnName("opisanie")
                        .HasMaxLength(100)
                        .IsUnicode(false);

                    b.Property<string>("Rolja")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<string>("Sik")
                        .IsRequired()
                        .HasColumnName("SIK")
                        .HasMaxLength(3)
                        .IsUnicode(false);

                    b.Property<string>("Spec")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<int>("Status")
                        .HasColumnName("status")
                        .HasColumnType("int(11)");

                    b.Property<string>("Tel")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<string>("User")
                        .IsRequired()
                        .HasColumnName("user")
                        .HasMaxLength(128)
                        .IsUnicode(false);

                    b.HasKey("Id");

                    b.ToTable("n_lica_import","votingregister");
                });

            modelBuilder.Entity("DataAccess.NLicaIzbori", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID")
                        .HasColumnType("int(7)");

                    b.Property<string>("CodeRolia")
                        .IsRequired()
                        .HasColumnName("Code_rolia")
                        .HasMaxLength(3)
                        .IsUnicode(false);

                    b.Property<int?>("Hasmaxincome")
                        .HasColumnName("hasmaxincome")
                        .HasColumnType("int(1) unsigned zerofill");

                    b.Property<int>("IdLice")
                        .HasColumnName("ID_Lice")
                        .HasColumnType("int(7)");

                    b.Property<int?>("IdSik")
                        .HasColumnName("Id_Sik")
                        .HasColumnType("int(10)");

                    b.Property<int?>("IdSila")
                        .HasColumnName("id_sila")
                        .HasColumnType("int(11)");

                    b.Property<string>("ImeRolia")
                        .HasColumnName("Ime_rolia")
                        .HasMaxLength(30)
                        .IsUnicode(false);

                    b.Property<string>("IzbAlias")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Izb_Alias")
                        .HasDefaultValueSql("MI2019")
                        .HasMaxLength(6)
                        .IsUnicode(false);

                    b.Property<DateTime?>("Koga")
                        .HasColumnName("KOGA");

                    b.Property<string>("Re")
                        .HasMaxLength(40)
                        .IsUnicode(false);

                    b.Property<string>("Toa")
                        .HasColumnName("TOA")
                        .HasMaxLength(2)
                        .IsUnicode(false);

                    b.Property<int?>("Tur")
                        .HasColumnType("int(1)");

                    b.Property<string>("User")
                        .HasColumnName("USER")
                        .HasMaxLength(128)
                        .IsUnicode(false);

                    b.HasKey("Id");

                    b.HasIndex("IdLice")
                        .HasName("n_lica_izbori_ibfk_1");

                    b.HasIndex("IdSik")
                        .HasName("FK_lica_izbori_siks_1");

                    b.HasIndex("IdSila")
                        .HasName("FK_lica_izbori_wnsila");

                    b.HasIndex("Toa")
                        .HasName("FK_n_lica_izbori_wntoa");

                    b.ToTable("n_lica_izbori","votingregister");
                });

            modelBuilder.Entity("DataAccess.NLicePariZanap", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int(8)");

                    b.Property<string>("CodeDancoef")
                        .HasColumnName("Code_dancoef")
                        .HasMaxLength(2)
                        .IsUnicode(false);

                    b.Property<int>("IdLice")
                        .HasColumnName("ID_Lice")
                        .HasColumnType("int(8)");

                    b.Property<DateTime?>("Koga");

                    b.Property<decimal?>("Pari")
                        .HasColumnType("decimal(10,4)");

                    b.HasKey("Id");

                    b.HasIndex("IdLice")
                        .HasName("FK_nlicaparizanap_nlica");

                    b.ToTable("n_lice_pari_zanap","votingregister");
                });

            modelBuilder.Entity("DataAccess.NLicePariZaplashtane", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int(8)");

                    b.Property<string>("CodePossition")
                        .HasColumnName("Code_possition")
                        .HasMaxLength(3)
                        .IsUnicode(false);

                    b.Property<string>("CodeTable")
                        .HasColumnName("Code_Table")
                        .HasColumnType("char(1)");

                    b.Property<int>("IdLice")
                        .HasColumnName("ID_Lice")
                        .HasColumnType("int(8)");

                    b.Property<DateTime?>("Koga");

                    b.Property<decimal?>("Pari")
                        .HasColumnType("decimal(10,4)");

                    b.HasKey("Id");

                    b.HasIndex("IdLice")
                        .HasName("FK_nlicaparizaplashtane_nlica");

                    b.ToTable("n_lice_pari_zaplashtane","votingregister");
                });

            modelBuilder.Entity("DataAccess.NListCodepositions", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID")
                        .HasColumnType("int(5)");

                    b.Property<string>("IzbAllias")
                        .IsRequired()
                        .HasColumnName("IZB_ALLIAS")
                        .HasMaxLength(6)
                        .IsUnicode(false);

                    b.Property<string>("Nime")
                        .HasColumnName("NIME")
                        .HasMaxLength(30)
                        .IsUnicode(false);

                    b.Property<int>("Nkode")
                        .HasColumnName("NKODE")
                        .HasColumnType("int(3)");

                    b.Property<int>("Pkode")
                        .HasColumnName("PKODE")
                        .HasColumnType("int(4)")
                        .HasDefaultValueSql("0");

                    b.Property<int?>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(1)")
                        .HasDefaultValueSql("1");

                    b.HasKey("Id");

                    b.HasIndex("Pkode")
                        .HasName("FK_CODEPOS_CODETABL");

                    b.ToTable("n_list_codepositions","votingregister");
                });

            modelBuilder.Entity("DataAccess.NListCodetables", b =>
                {
                    b.Property<int>("Nkode")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("NKODE")
                        .HasColumnType("int(4)");

                    b.Property<string>("Nime")
                        .HasColumnName("NIME")
                        .HasMaxLength(30)
                        .IsUnicode(false);

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(1)")
                        .HasDefaultValueSql("1");

                    b.HasKey("Nkode");

                    b.ToTable("n_list_codetables","votingregister");
                });

            modelBuilder.Entity("DataAccess.NLog", b =>
                {
                    b.Property<int>("IdLog")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Id_LOG")
                        .HasColumnType("int(11)");

                    b.Property<int?>("Aaa")
                        .HasColumnName("AAA")
                        .HasColumnType("int(1)");

                    b.Property<int>("Action")
                        .HasColumnName("ACTION")
                        .HasColumnType("int(11)");

                    b.Property<string>("ImeObrabotka")
                        .IsRequired()
                        .HasColumnName("Ime_Obrabotka")
                        .HasMaxLength(250)
                        .IsUnicode(false);

                    b.Property<string>("KodObrabotka")
                        .IsRequired()
                        .HasColumnName("Kod_Obrabotka")
                        .HasMaxLength(4)
                        .IsUnicode(false);

                    b.Property<DateTime>("Koga");

                    b.Property<string>("User")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false);

                    b.HasKey("IdLog");

                    b.ToTable("n_log","votingregister");
                });

            modelBuilder.Entity("DataAccess.NNomenclatures", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("int(11)");

                    b.Property<string>("Description")
                        .HasColumnName("description")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<short?>("Status")
                        .HasColumnName("status")
                        .HasColumnType("smallint(1)");

                    b.Property<string>("Table")
                        .HasColumnName("table")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.HasKey("Id");

                    b.ToTable("n_nomenclatures","votingregister");
                });

            modelBuilder.Entity("DataAccess.NStatistics", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("int(11)");

                    b.Property<string>("Longdescription")
                        .HasColumnName("longdescription")
                        .HasMaxLength(250)
                        .IsUnicode(false);

                    b.Property<string>("Shortdescription")
                        .HasColumnName("shortdescription")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.HasKey("Id");

                    b.ToTable("n_statistics","votingregister");
                });

            modelBuilder.Entity("DataAccess.NToaMain", b =>
                {
                    b.Property<int>("Nrec")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)");

                    b.Property<int?>("Ano")
                        .HasColumnName("ANO")
                        .HasColumnType("int(11)");

                    b.Property<string>("Ap")
                        .HasColumnName("AP")
                        .HasMaxLength(3)
                        .IsUnicode(false);

                    b.Property<string>("Blok")
                        .HasColumnName("BLOK")
                        .HasMaxLength(5)
                        .IsUnicode(false);

                    b.Property<string>("Bul")
                        .HasMaxLength(13)
                        .IsUnicode(false);

                    b.Property<string>("Epod")
                        .HasColumnName("EPOD")
                        .HasMaxLength(30)
                        .IsUnicode(false);

                    b.Property<string>("Et")
                        .HasColumnName("ET")
                        .HasMaxLength(2)
                        .IsUnicode(false);

                    b.Property<string>("Ime")
                        .HasColumnName("IME")
                        .HasMaxLength(30)
                        .IsUnicode(false);

                    b.Property<string>("Ipod")
                        .HasColumnName("IPOD")
                        .HasMaxLength(20)
                        .IsUnicode(false);

                    b.Property<string>("IzbAlias")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("IZB_ALIAS")
                        .HasDefaultValueSql("MI2019")
                        .HasMaxLength(6)
                        .IsUnicode(false);

                    b.Property<string>("Izr")
                        .HasMaxLength(15)
                        .IsUnicode(false);

                    b.Property<string>("JkKv")
                        .HasColumnName("JK_KV")
                        .HasMaxLength(2)
                        .IsUnicode(false);

                    b.Property<string>("Nas")
                        .HasColumnName("NAS")
                        .HasMaxLength(5)
                        .IsUnicode(false);

                    b.Property<string>("Nom")
                        .HasColumnName("NOM")
                        .HasMaxLength(4)
                        .IsUnicode(false);

                    b.Property<int?>("Nsik")
                        .HasColumnType("int(11)");

                    b.Property<string>("Obl")
                        .HasColumnName("OBL")
                        .HasMaxLength(3)
                        .IsUnicode(false);

                    b.Property<string>("Obs")
                        .HasColumnName("OBS")
                        .HasMaxLength(5)
                        .IsUnicode(false);

                    b.Property<string>("Pk")
                        .HasColumnName("PK")
                        .HasMaxLength(4)
                        .IsUnicode(false);

                    b.Property<string>("Pred")
                        .HasMaxLength(20)
                        .IsUnicode(false);

                    b.Property<string>("Pris")
                        .HasMaxLength(10)
                        .IsUnicode(false);

                    b.Property<string>("R1")
                        .HasMaxLength(20)
                        .IsUnicode(false);

                    b.Property<string>("R2")
                        .HasMaxLength(20)
                        .IsUnicode(false);

                    b.Property<string>("Raj")
                        .HasColumnName("RAJ")
                        .HasMaxLength(2)
                        .IsUnicode(false);

                    b.Property<string>("Sekr")
                        .HasMaxLength(20)
                        .IsUnicode(false);

                    b.Property<int?>("StatusMaster")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Status_Master")
                        .HasColumnType("int(1)")
                        .HasDefaultValueSql("1");

                    b.Property<string>("Tel")
                        .HasColumnName("TEL")
                        .HasMaxLength(10)
                        .IsUnicode(false);

                    b.Property<string>("Tel1")
                        .HasMaxLength(10)
                        .IsUnicode(false);

                    b.Property<string>("Toa")
                        .HasColumnName("TOA")
                        .HasMaxLength(2)
                        .IsUnicode(false);

                    b.Property<sbyte>("Tur")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValueSql("1");

                    b.Property<string>("Ul")
                        .HasColumnName("UL")
                        .HasMaxLength(5)
                        .IsUnicode(false);

                    b.Property<string>("Vh")
                        .HasColumnName("VH")
                        .HasMaxLength(2)
                        .IsUnicode(false);

                    b.HasKey("Nrec");

                    b.HasIndex("JkKv")
                        .HasName("JK_KV");

                    b.HasIndex("Nas")
                        .HasName("NAS");

                    b.HasIndex("Obl")
                        .HasName("OBL");

                    b.HasIndex("Obs")
                        .HasName("OBS");

                    b.HasIndex("Raj")
                        .HasName("RAJ");

                    b.HasIndex("Toa")
                        .HasName("FK_MASTER_WNTOA");

                    b.HasIndex("Ul")
                        .HasName("UL");

                    b.ToTable("n_toa_main","votingregister");
                });

            modelBuilder.Entity("DataAccess.NTopDancoef", b =>
                {
                    b.Property<int>("IdCoef")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID_Coef")
                        .HasColumnType("int(6)");

                    b.Property<decimal?>("CoefStoinost")
                        .HasColumnName("Coef_stoinost")
                        .HasColumnType("decimal(6,4)");

                    b.Property<string>("FieldNameNew")
                        .HasColumnName("Field_name_NEW")
                        .HasMaxLength(10)
                        .IsUnicode(false);

                    b.Property<string>("FieldlNameOld")
                        .HasColumnName("Fieldl_name_OLD")
                        .HasMaxLength(10)
                        .IsUnicode(false);

                    b.Property<string>("IzbAllias")
                        .IsRequired()
                        .HasColumnName("IZB_ALLIAS")
                        .HasMaxLength(6)
                        .IsUnicode(false);

                    b.Property<string>("Nred")
                        .IsRequired()
                        .HasMaxLength(2)
                        .IsUnicode(false);

                    b.Property<int?>("StatusCoef")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Status_coef")
                        .HasColumnType("int(1)")
                        .HasDefaultValueSql("0");

                    b.Property<string>("Tekst")
                        .HasMaxLength(60)
                        .IsUnicode(false);

                    b.HasKey("IdCoef");

                    b.ToTable("n_top_dancoef","votingregister");
                });

            modelBuilder.Entity("DataAccess.NTopMain", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID")
                        .HasColumnType("int(6)");

                    b.Property<DateTime?>("Date1tur")
                        .HasColumnName("DATE1TUR");

                    b.Property<DateTime?>("Date2tur")
                        .HasColumnName("DATE2TUR");

                    b.Property<string>("Description")
                        .HasMaxLength(40)
                        .IsUnicode(false);

                    b.Property<string>("IzbAlias")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("IZB_ALIAS")
                        .HasDefaultValueSql("NULL")
                        .HasMaxLength(6)
                        .IsUnicode(false);

                    b.Property<int?>("StatusParameters")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Status_parameters")
                        .HasColumnType("int(1)")
                        .HasDefaultValueSql("1");

                    b.HasKey("Id");

                    b.ToTable("n_top_main","votingregister");
                });

            modelBuilder.Entity("DataAccess.NTopParameters", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID")
                        .HasColumnType("int(6)");

                    b.Property<string>("Description")
                        .HasMaxLength(40)
                        .IsUnicode(false);

                    b.Property<string>("IzbAlias")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnName("IZB_ALIAS")
                        .HasDefaultValueSql("MI2019")
                        .HasMaxLength(6)
                        .IsUnicode(false);

                    b.Property<string>("Kod")
                        .IsRequired()
                        .HasColumnName("KOD")
                        .HasMaxLength(2)
                        .IsUnicode(false);

                    b.Property<int?>("StatusParameters")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Status_parameters")
                        .HasColumnType("int(1)")
                        .HasDefaultValueSql("1");

                    b.Property<string>("Znachenie")
                        .HasMaxLength(40)
                        .IsUnicode(false);

                    b.HasKey("Id");

                    b.ToTable("n_top_parameters","votingregister");
                });

            modelBuilder.Entity("DataAccess.NTopPartkvoti", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int(6)");

                    b.Property<string>("CodeWnsila")
                        .HasColumnName("code_wnsila")
                        .HasMaxLength(2)
                        .IsUnicode(false);

                    b.Property<string>("IzbAlias")
                        .IsRequired()
                        .HasColumnName("Izb_Alias")
                        .HasMaxLength(6)
                        .IsUnicode(false);

                    b.Property<string>("IzbRajon")
                        .HasColumnName("Izb_rajon")
                        .HasMaxLength(2)
                        .IsUnicode(false);

                    b.Property<DateTime?>("Koga")
                        .HasColumnName("KOGA");

                    b.Property<int?>("SikClenove")
                        .HasColumnName("SIK_Clenove")
                        .HasColumnType("int(4)");

                    b.Property<int?>("SikHeads")
                        .HasColumnName("SIK_HEADS")
                        .HasColumnType("int(4)");

                    b.Property<int?>("StatusKvoti")
                        .HasColumnName("Status_kvoti")
                        .HasColumnType("int(1)");

                    b.Property<string>("Toa")
                        .HasColumnName("TOA")
                        .HasMaxLength(2)
                        .IsUnicode(false);

                    b.Property<string>("User")
                        .HasColumnName("USER")
                        .HasMaxLength(20)
                        .IsUnicode(false);

                    b.HasKey("Id");

                    b.ToTable("n_top_partkvoti","votingregister");
                });

            modelBuilder.Entity("DataAccess.NormiOperacii", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnName("ID")
                        .HasColumnType("int(7)");

                    b.Property<string>("IzbAllias")
                        .HasColumnName("Izb_allias")
                        .HasMaxLength(6)
                        .IsUnicode(false);

                    b.Property<DateTime?>("Koga");

                    b.Property<decimal?>("Pari")
                        .HasColumnType("decimal(6,2)");

                    b.Property<int?>("Status")
                        .HasColumnType("int(1)");

                    b.Property<int?>("Tur")
                        .HasColumnType("int(1)");

                    b.Property<string>("User")
                        .HasMaxLength(128)
                        .IsUnicode(false);

                    b.Property<string>("VidCodetable")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Vid_codetable")
                        .HasColumnType("char(1)")
                        .HasDefaultValueSql("3");

                    b.Property<string>("VidOperacia")
                        .HasColumnName("Vid_operacia")
                        .HasMaxLength(3)
                        .IsUnicode(false);

                    b.HasKey("Id");

                    b.ToTable("normi_operacii","votingregister");
                });

            modelBuilder.Entity("DataAccess.NormiPriznaci", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnName("ID")
                        .HasColumnType("int(7)");

                    b.Property<string>("IzbAllias")
                        .HasColumnName("Izb_allias")
                        .HasMaxLength(6)
                        .IsUnicode(false);

                    b.Property<DateTime?>("Koga");

                    b.Property<decimal?>("Pari")
                        .HasColumnType("decimal(6,2)");

                    b.Property<int?>("Status")
                        .HasColumnType("int(1)");

                    b.Property<int?>("Tur")
                        .HasColumnType("int(1)");

                    b.Property<string>("User")
                        .HasMaxLength(128)
                        .IsUnicode(false);

                    b.Property<string>("VidCodetable")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Vid_codetable")
                        .HasColumnType("char(1)")
                        .HasDefaultValueSql("2");

                    b.Property<string>("VidPriznak")
                        .HasColumnName("Vid_priznak")
                        .HasMaxLength(3)
                        .IsUnicode(false);

                    b.HasKey("Id");

                    b.ToTable("normi_priznaci","votingregister");
                });

            modelBuilder.Entity("DataAccess.NormiRoli", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnName("ID")
                        .HasColumnType("int(7)");

                    b.Property<string>("IzbAllias")
                        .HasColumnName("Izb_allias")
                        .HasMaxLength(6)
                        .IsUnicode(false);

                    b.Property<DateTime?>("Koga");

                    b.Property<decimal?>("Pari")
                        .HasColumnType("decimal(6,2)");

                    b.Property<int?>("Status")
                        .HasColumnType("int(1)");

                    b.Property<int?>("Tur")
                        .HasColumnType("int(1)");

                    b.Property<string>("User")
                        .HasMaxLength(128)
                        .IsUnicode(false);

                    b.Property<string>("VidCodetable")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Vid_codetable")
                        .HasColumnType("char(1)")
                        .HasDefaultValueSql("1");

                    b.Property<string>("VidCodetale2")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Vid_codetale_2")
                        .HasColumnType("char(1)")
                        .HasDefaultValueSql("4");

                    b.Property<string>("VidRolia")
                        .HasColumnName("Vid_rolia")
                        .HasMaxLength(3)
                        .IsUnicode(false);

                    b.Property<string>("VidSekcia")
                        .HasColumnName("Vid_sekcia")
                        .HasMaxLength(3)
                        .IsUnicode(false);

                    b.HasKey("Id");

                    b.ToTable("normi_roli","votingregister");
                });

            modelBuilder.Entity("DataAccess.Siks", b =>
                {
                    b.Property<int>("IdSek")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Id_sek")
                        .HasColumnType("int(10)");

                    b.Property<string>("AaBbCc")
                        .IsRequired()
                        .HasColumnName("AA_BB_CC")
                        .HasMaxLength(6)
                        .IsUnicode(false);

                    b.Property<string>("AdrIme")
                        .HasColumnName("ADR_IME")
                        .HasMaxLength(60)
                        .IsUnicode(false);

                    b.Property<string>("Blok")
                        .HasColumnName("BLok")
                        .HasMaxLength(5)
                        .IsUnicode(false);

                    b.Property<string>("IzbAlias")
                        .IsRequired()
                        .HasColumnName("Izb_Alias")
                        .HasMaxLength(6)
                        .IsUnicode(false);

                    b.Property<string>("IzbRajon")
                        .IsRequired()
                        .HasColumnName("Izb_rajon")
                        .HasMaxLength(2)
                        .IsUnicode(false);

                    b.Property<string>("JkKv")
                        .HasColumnName("JK_KV")
                        .HasMaxLength(2)
                        .IsUnicode(false);

                    b.Property<DateTime?>("Koga");

                    b.Property<string>("Nas")
                        .HasColumnName("NAS")
                        .HasMaxLength(5)
                        .IsUnicode(false);

                    b.Property<string>("Nom")
                        .HasMaxLength(5)
                        .IsUnicode(false);

                    b.Property<string>("Obl")
                        .HasMaxLength(3)
                        .IsUnicode(false);

                    b.Property<string>("Obs")
                        .HasMaxLength(5)
                        .IsUnicode(false);

                    b.Property<string>("Sik")
                        .IsRequired()
                        .HasMaxLength(3)
                        .IsUnicode(false);

                    b.Property<int>("StatusSekcia")
                        .HasColumnName("Status_Sekcia")
                        .HasColumnType("int(1)");

                    b.Property<string>("Tel")
                        .HasMaxLength(10)
                        .IsUnicode(false);

                    b.Property<string>("Toa")
                        .IsRequired()
                        .HasColumnName("TOA")
                        .HasMaxLength(2)
                        .IsUnicode(false);

                    b.Property<int?>("Tur")
                        .HasColumnName("TUR")
                        .HasColumnType("int(1)");

                    b.Property<string>("Ul")
                        .HasColumnName("UL")
                        .HasMaxLength(5)
                        .IsUnicode(false);

                    b.Property<string>("User")
                        .HasColumnName("USER")
                        .HasMaxLength(128)
                        .IsUnicode(false);

                    b.HasKey("IdSek");

                    b.HasIndex("JkKv")
                        .HasName("JK_KV");

                    b.HasIndex("Nas")
                        .HasName("NAS");

                    b.HasIndex("Obl")
                        .HasName("Obl");

                    b.HasIndex("Obs")
                        .HasName("Obs");

                    b.HasIndex("Toa")
                        .HasName("FK_SIKS_WNTOA");

                    b.HasIndex("Ul")
                        .HasName("UL");

                    b.ToTable("siks","votingregister");
                });

            modelBuilder.Entity("DataAccess.SiksVidove", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID")
                        .HasColumnType("int(7)");

                    b.Property<int>("Codeposition")
                        .HasMaxLength(3)
                        .IsUnicode(false);

                    b.Property<int>("Codetable")
                        .HasColumnType("int(11)");

                    b.Property<int>("IdSik")
                        .HasColumnName("Id_Sik")
                        .HasColumnType("int(11)");

                    b.Property<string>("IzbAllias")
                        .IsRequired()
                        .HasColumnName("IZB_allias")
                        .HasMaxLength(6)
                        .IsUnicode(false);

                    b.Property<int?>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(1)")
                        .HasDefaultValueSql("1");

                    b.Property<int>("Tur")
                        .HasColumnType("int(1)");

                    b.HasKey("Id");

                    b.HasIndex("IdSik")
                        .HasName("FK_SIKS_VIDOVE_SIKS");

                    b.ToTable("siks_vidove","votingregister");
                });

            modelBuilder.Entity("DataAccess.SysTables", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnName("id")
                        .HasColumnType("int(11)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnName("name")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.HasKey("Id");

                    b.ToTable("sys_tables","votingregister");
                });

            modelBuilder.Entity("DataAccess.Wnasm", b =>
                {
                    b.Property<string>("Nkod")
                        .HasColumnName("nkod")
                        .HasMaxLength(5)
                        .IsUnicode(false);

                    b.Property<string>("Kmetstvo")
                        .HasMaxLength(8)
                        .IsUnicode(false);

                    b.Property<string>("Nime")
                        .HasColumnName("nime")
                        .HasMaxLength(25)
                        .IsUnicode(false);

                    b.HasKey("Nkod");

                    b.ToTable("wnasm","votingregister");
                });

            modelBuilder.Entity("DataAccess.Wndocs", b =>
                {
                    b.Property<string>("Nkod")
                        .HasColumnName("NKOD")
                        .HasMaxLength(2)
                        .IsUnicode(false);

                    b.Property<string>("IzbAlias")
                        .HasColumnName("Izb_Alias")
                        .HasMaxLength(6)
                        .IsUnicode(false);

                    b.Property<string>("Nime")
                        .HasColumnName("NIME")
                        .HasMaxLength(40)
                        .IsUnicode(false);

                    b.Property<sbyte?>("StatusNdocs")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Status_ndocs")
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValueSql("1");

                    b.HasKey("Nkod");

                    b.ToTable("wndocs","votingregister");
                });

            modelBuilder.Entity("DataAccess.WnjkKv", b =>
                {
                    b.Property<string>("Nkod")
                        .HasColumnName("nkod")
                        .HasMaxLength(5)
                        .IsUnicode(false);

                    b.Property<string>("Nime")
                        .HasColumnName("nime")
                        .HasMaxLength(30)
                        .IsUnicode(false);

                    b.HasKey("Nkod");

                    b.ToTable("wnjk_kv","votingregister");
                });

            modelBuilder.Entity("DataAccess.Wnkmetstva", b =>
                {
                    b.Property<string>("Nkod")
                        .HasColumnName("nkod")
                        .HasMaxLength(10)
                        .IsUnicode(false);

                    b.Property<string>("Nime")
                        .HasColumnName("nime")
                        .HasMaxLength(40)
                        .IsUnicode(false);

                    b.HasKey("Nkod");

                    b.ToTable("wnkmetstva","votingregister");
                });

            modelBuilder.Entity("DataAccess.Wnmaks", b =>
                {
                    b.Property<int>("IdShablon")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID_shablon")
                        .HasColumnType("int(5)");

                    b.Property<string>("IzbAlias")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Izb_Alias")
                        .HasDefaultValueSql("MI2019")
                        .HasMaxLength(6)
                        .IsUnicode(false);

                    b.Property<string>("Nime")
                        .HasColumnName("NIME")
                        .HasMaxLength(40)
                        .IsUnicode(false);

                    b.Property<string>("Nkod")
                        .HasColumnName("NKOD")
                        .HasMaxLength(10)
                        .IsUnicode(false);

                    b.Property<sbyte?>("StatusSh")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Status_sh")
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValueSql("0");

                    b.HasKey("IdShablon");

                    b.ToTable("wnmaks","votingregister");
                });

            modelBuilder.Entity("DataAccess.Wnnaz", b =>
                {
                    b.Property<string>("Nkod")
                        .HasColumnName("NKOD")
                        .HasMaxLength(2)
                        .IsUnicode(false);

                    b.Property<string>("Nime")
                        .HasColumnName("NIME")
                        .HasMaxLength(25)
                        .IsUnicode(false);

                    b.HasKey("Nkod");

                    b.ToTable("wnnaz","votingregister");
                });

            modelBuilder.Entity("DataAccess.Wnnru", b =>
                {
                    b.Property<string>("Nkod")
                        .HasColumnName("NKOD")
                        .HasMaxLength(2)
                        .IsUnicode(false);

                    b.Property<string>("Nime")
                        .HasColumnName("NIME")
                        .HasMaxLength(30)
                        .IsUnicode(false);

                    b.HasKey("Nkod");

                    b.ToTable("wnnru","votingregister");
                });

            modelBuilder.Entity("DataAccess.Wnobl", b =>
                {
                    b.Property<string>("Nkod")
                        .HasColumnName("NKOD")
                        .HasMaxLength(3)
                        .IsUnicode(false);

                    b.Property<string>("Nime")
                        .HasColumnName("NIME")
                        .HasMaxLength(30)
                        .IsUnicode(false);

                    b.HasKey("Nkod");

                    b.ToTable("wnobl","votingregister");
                });

            modelBuilder.Entity("DataAccess.Wnobs", b =>
                {
                    b.Property<string>("Nkod")
                        .HasColumnName("NKOD")
                        .HasMaxLength(5)
                        .IsUnicode(false);

                    b.Property<string>("Ekatte")
                        .HasColumnName("ekatte")
                        .HasMaxLength(5)
                        .IsUnicode(false);

                    b.Property<string>("Nime")
                        .HasColumnName("NIME")
                        .HasMaxLength(28)
                        .IsUnicode(false);

                    b.HasKey("Nkod");

                    b.ToTable("wnobs","votingregister");
                });

            modelBuilder.Entity("DataAccess.Wnsila", b =>
                {
                    b.Property<int>("IdParty")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID_Party")
                        .HasColumnType("int(5)");

                    b.Property<string>("IzbAlias")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnName("IZB_ALIAS")
                        .HasDefaultValueSql("0")
                        .HasMaxLength(6)
                        .IsUnicode(false);

                    b.Property<string>("LegalKod")
                        .HasColumnName("Legal_Kod")
                        .HasMaxLength(3)
                        .IsUnicode(false);

                    b.Property<string>("Nime")
                        .HasColumnName("NIME")
                        .HasMaxLength(40)
                        .IsUnicode(false);

                    b.Property<string>("Nkod")
                        .IsRequired()
                        .HasColumnName("NKOD")
                        .HasMaxLength(2)
                        .IsUnicode(false);

                    b.Property<string>("ShortName")
                        .HasColumnName("Short_name")
                        .HasMaxLength(15)
                        .IsUnicode(false);

                    b.Property<int?>("StatusPartii")
                        .HasColumnName("Status_Partii")
                        .HasColumnType("int(1)");

                    b.HasKey("IdParty");

                    b.ToTable("wnsila","votingregister");
                });

            modelBuilder.Entity("DataAccess.Wnspec", b =>
                {
                    b.Property<string>("Nkod")
                        .HasColumnName("NKOD")
                        .HasMaxLength(2)
                        .IsUnicode(false);

                    b.Property<string>("Nime")
                        .HasColumnName("NIME")
                        .HasMaxLength(16)
                        .IsUnicode(false);

                    b.HasKey("Nkod");

                    b.ToTable("wnspec","votingregister");
                });

            modelBuilder.Entity("DataAccess.Wnszem", b =>
                {
                    b.Property<string>("Nkod")
                        .HasColumnName("NKOD")
                        .HasMaxLength(2)
                        .IsUnicode(false);

                    b.Property<string>("Nime")
                        .HasColumnName("NIME")
                        .HasMaxLength(16)
                        .IsUnicode(false);

                    b.HasKey("Nkod");

                    b.ToTable("wnszem","votingregister");
                });

            modelBuilder.Entity("DataAccess.Wntoa", b =>
                {
                    b.Property<string>("Nkod")
                        .HasColumnName("NKOD")
                        .HasMaxLength(2)
                        .IsUnicode(false);

                    b.Property<string>("Nime")
                        .HasColumnName("NIME")
                        .HasMaxLength(16)
                        .IsUnicode(false);

                    b.HasKey("Nkod");

                    b.ToTable("wntoa","votingregister");
                });

            modelBuilder.Entity("DataAccess.WntoaIzbraion", b =>
                {
                    b.Property<string>("Nkod")
                        .HasColumnName("NKOD")
                        .HasMaxLength(2)
                        .IsUnicode(false);

                    b.Property<int?>("BroiSik")
                        .HasColumnName("BROI_SIK")
                        .HasColumnType("int(11)");

                    b.Property<string>("IzbR")
                        .HasColumnName("IZB_R")
                        .HasMaxLength(2)
                        .IsUnicode(false);

                    b.Property<string>("Nime")
                        .HasColumnName("NIME")
                        .HasMaxLength(16)
                        .IsUnicode(false);

                    b.HasKey("Nkod");

                    b.ToTable("wntoa_izbraion","votingregister");
                });

            modelBuilder.Entity("DataAccess.Wnuli", b =>
                {
                    b.Property<string>("Nkod")
                        .HasColumnName("nkod")
                        .HasMaxLength(5)
                        .IsUnicode(false);

                    b.Property<string>("Nime")
                        .HasColumnName("nime")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<string>("WnasmNkod")
                        .HasColumnName("wnasm_nkod")
                        .HasMaxLength(5)
                        .IsUnicode(false);

                    b.Property<string>("WnuliNkod")
                        .HasColumnName("wnuli_nkod")
                        .HasMaxLength(5)
                        .IsUnicode(false);

                    b.HasKey("Nkod");

                    b.ToTable("wnuli","votingregister");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("Name")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<string>("RoleId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AccessFailedCount");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("Discriminator")
                        .IsRequired();

                    b.Property<string>("Email")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed");

                    b.Property<bool>("LockoutEnabled");

                    b.Property<DateTimeOffset?>("LockoutEnd");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256);

                    b.Property<string>("PasswordHash");

                    b.Property<string>("PhoneNumber");

                    b.Property<bool>("PhoneNumberConfirmed");

                    b.Property<string>("SecurityStamp");

                    b.Property<bool>("TwoFactorEnabled");

                    b.Property<string>("UserName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex");

                    b.ToTable("AspNetUsers");

                    b.HasDiscriminator<string>("Discriminator").HasValue("IdentityUser");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider");

                    b.Property<string>("ProviderKey");

                    b.Property<string>("ProviderDisplayName");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId");

                    b.Property<string>("RoleId");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId");

                    b.Property<string>("LoginProvider");

                    b.Property<string>("Name");

                    b.Property<string>("Value");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("Common.ViewModels.User.SSOUserIdentity", b =>
                {
                    b.HasBaseType("Microsoft.AspNetCore.Identity.IdentityUser");

                    b.Property<string>("Administrative_Rajon");

                    b.Property<string>("Names");

                    b.Property<int?>("Ot_Partiq");

                    b.HasDiscriminator().HasValue("SSOUserIdentity");
                });

            modelBuilder.Entity("DataAccess.Aspnetroleclaims", b =>
                {
                    b.HasOne("DataAccess.Aspnetroles", "Role")
                        .WithMany("Aspnetroleclaims")
                        .HasForeignKey("RoleId")
                        .HasConstraintName("FK_AspNetRoleClaims_AspNetRoles_RoleId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("DataAccess.Aspnetuserclaims", b =>
                {
                    b.HasOne("DataAccess.Aspnetusers", "User")
                        .WithMany("Aspnetuserclaims")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK_AspNetUserClaims_AspNetUsers_UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("DataAccess.Aspnetuserlogins", b =>
                {
                    b.HasOne("DataAccess.Aspnetusers", "User")
                        .WithMany("Aspnetuserlogins")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK_AspNetUserLogins_AspNetUsers_UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("DataAccess.Aspnetuserroles", b =>
                {
                    b.HasOne("DataAccess.Aspnetroles", "Role")
                        .WithMany("Aspnetuserroles")
                        .HasForeignKey("RoleId")
                        .HasConstraintName("FK_AspNetUserRoles_AspNetRoles_RoleId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("DataAccess.Aspnetusers", "User")
                        .WithMany("Aspnetuserroles")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK_AspNetUserRoles_AspNetUsers_UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("DataAccess.Aspnetusers", b =>
                {
                    b.HasOne("DataAccess.Wntoa", "AdministrativeRajonNavigation")
                        .WithMany("Aspnetusers")
                        .HasForeignKey("AdministrativeRajon")
                        .HasConstraintName("FK_aspnetusers_wntoa_RajonNkod");

                    b.HasOne("DataAccess.Wnsila", "OtPartiqNavigation")
                        .WithMany("Aspnetusers")
                        .HasForeignKey("OtPartiq")
                        .HasConstraintName("FK_aspnetusers_sila_PartiqIdParty");
                });

            modelBuilder.Entity("DataAccess.Aspnetusertokens", b =>
                {
                    b.HasOne("DataAccess.Aspnetusers", "User")
                        .WithMany("Aspnetusertokens")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK_AspNetUserTokens_AspNetUsers_UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("DataAccess.NLicaDopylnenie", b =>
                {
                    b.HasOne("DataAccess.NLicaIzbori", "IdLiceNavigation")
                        .WithMany("NLicaDopylnenie")
                        .HasForeignKey("IdLice")
                        .HasConstraintName("FK_nlicadop_nlica");
                });

            modelBuilder.Entity("DataAccess.NLicaIzbori", b =>
                {
                    b.HasOne("DataAccess.NLica", "IdLiceNavigation")
                        .WithMany("NLicaIzbori")
                        .HasForeignKey("IdLice")
                        .HasConstraintName("n_lica_izbori_ibfk_1");

                    b.HasOne("DataAccess.Wnsila", "IdSilaNavigation")
                        .WithMany("NLicaIzbori")
                        .HasForeignKey("IdSila")
                        .HasConstraintName("FK_lica_izbori_wnsila");

                    b.HasOne("DataAccess.Wntoa", "ToaNavigation")
                        .WithMany("NLicaIzbori")
                        .HasForeignKey("Toa")
                        .HasConstraintName("FK_n_lica_izbori_wntoa");
                });

            modelBuilder.Entity("DataAccess.NLicePariZanap", b =>
                {
                    b.HasOne("DataAccess.NLicaIzbori", "IdLiceNavigation")
                        .WithMany("NLicePariZanap")
                        .HasForeignKey("IdLice")
                        .HasConstraintName("FK_nlicaparizanap_nlica");
                });

            modelBuilder.Entity("DataAccess.NLicePariZaplashtane", b =>
                {
                    b.HasOne("DataAccess.NLicaIzbori", "IdLiceNavigation")
                        .WithMany("NLicePariZaplashtane")
                        .HasForeignKey("IdLice")
                        .HasConstraintName("FK_nlicaparizaplashtane_nlica");
                });

            modelBuilder.Entity("DataAccess.NListCodepositions", b =>
                {
                    b.HasOne("DataAccess.NListCodetables", "PkodeNavigation")
                        .WithMany("NListCodepositions")
                        .HasForeignKey("Pkode")
                        .HasConstraintName("FK_CODEPOS_CODETABL");
                });

            modelBuilder.Entity("DataAccess.NToaMain", b =>
                {
                    b.HasOne("DataAccess.WnjkKv", "JkKvNavigation")
                        .WithMany("NToaMain")
                        .HasForeignKey("JkKv")
                        .HasConstraintName("n_toa_main_ibfk_8");

                    b.HasOne("DataAccess.Wnasm", "NasNavigation")
                        .WithMany("NToaMain")
                        .HasForeignKey("Nas")
                        .HasConstraintName("n_toa_main_ibfk_3");

                    b.HasOne("DataAccess.Wnobl", "OblNavigation")
                        .WithMany("NToaMain")
                        .HasForeignKey("Obl")
                        .HasConstraintName("n_toa_main_ibfk_5");

                    b.HasOne("DataAccess.Wnobs", "ObsNavigation")
                        .WithMany("NToaMain")
                        .HasForeignKey("Obs")
                        .HasConstraintName("n_toa_main_ibfk_6");

                    b.HasOne("DataAccess.Wntoa", "RajNavigation")
                        .WithMany("NToaMainRajNavigation")
                        .HasForeignKey("Raj")
                        .HasConstraintName("n_toa_main_ibfk_1");

                    b.HasOne("DataAccess.Wntoa", "ToaNavigation")
                        .WithMany("NToaMainToaNavigation")
                        .HasForeignKey("Toa")
                        .HasConstraintName("FK_MASTER_WNTOA");

                    b.HasOne("DataAccess.Wnuli", "UlNavigation")
                        .WithMany("NToaMain")
                        .HasForeignKey("Ul")
                        .HasConstraintName("n_toa_main_ibfk_7");
                });

            modelBuilder.Entity("DataAccess.Siks", b =>
                {
                    b.HasOne("DataAccess.Wnasm", "NasNavigation")
                        .WithMany("Siks")
                        .HasForeignKey("Nas")
                        .HasConstraintName("siks_ibfk_3");

                    b.HasOne("DataAccess.Wnobl", "OblNavigation")
                        .WithMany("Siks")
                        .HasForeignKey("Obl")
                        .HasConstraintName("siks_ibfk_1");

                    b.HasOne("DataAccess.Wnobs", "ObsNavigation")
                        .WithMany("Siks")
                        .HasForeignKey("Obs")
                        .HasConstraintName("siks_ibfk_2");

                    b.HasOne("DataAccess.Wntoa", "ToaNavigation")
                        .WithMany("Siks")
                        .HasForeignKey("Toa")
                        .HasConstraintName("FK_SIKS_WNTOA");
                });

            modelBuilder.Entity("DataAccess.SiksVidove", b =>
                {
                    b.HasOne("DataAccess.Siks", "IdSikNavigation")
                        .WithMany("SiksVidove")
                        .HasForeignKey("IdSik")
                        .HasConstraintName("FK_SIKS_VIDOVE_SIKS");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
