//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegiXClient.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://egov.bg/RegiX", ConfigurationName="ServiceReference1.IRegiXEntryPointV2")]
    public interface IRegiXEntryPointV2 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://egov.bg/RegiX/IRegiXEntryPointV2/Execute", ReplyAction="http://egov.bg/RegiX/IRegiXEntryPointV2/ExecuteResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AccessMatrixType))]
        RegiXClient.ServiceReference1.ResultWrapper Execute(RegiXClient.ServiceReference1.RequestWrapper request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://egov.bg/RegiX/IRegiXEntryPointV2/Execute", ReplyAction="http://egov.bg/RegiX/IRegiXEntryPointV2/ExecuteResponse")]
        System.Threading.Tasks.Task<RegiXClient.ServiceReference1.ResultWrapper> ExecuteAsync(RegiXClient.ServiceReference1.RequestWrapper request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://egov.bg/RegiX/IRegiXEntryPointV2/CheckResult", ReplyAction="http://egov.bg/RegiX/IRegiXEntryPointV2/CheckResultResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AccessMatrixType))]
        RegiXClient.ServiceReference1.ResultWrapper CheckResult(RegiXClient.ServiceReference1.ServiceCheckResultWrapper argument);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://egov.bg/RegiX/IRegiXEntryPointV2/CheckResult", ReplyAction="http://egov.bg/RegiX/IRegiXEntryPointV2/CheckResultResponse")]
        System.Threading.Tasks.Task<RegiXClient.ServiceReference1.ResultWrapper> CheckResultAsync(RegiXClient.ServiceReference1.ServiceCheckResultWrapper argument);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://egov.bg/RegiX/IRegiXEntryPointV2/AcknowledgeResultReceived", ReplyAction="http://egov.bg/RegiX/IRegiXEntryPointV2/AcknowledgeResultReceivedResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AccessMatrixType))]
        void AcknowledgeResultReceived(RegiXClient.ServiceReference1.ServiceCheckResultWrapper argument);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://egov.bg/RegiX/IRegiXEntryPointV2/AcknowledgeResultReceived", ReplyAction="http://egov.bg/RegiX/IRegiXEntryPointV2/AcknowledgeResultReceivedResponse")]
        System.Threading.Tasks.Task AcknowledgeResultReceivedAsync(RegiXClient.ServiceReference1.ServiceCheckResultWrapper argument);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://egov.bg/RegiX/IRegiXEntryPointV2/ExecuteCallback", ReplyAction="http://egov.bg/RegiX/IRegiXEntryPointV2/ExecuteCallbackResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AccessMatrixType))]
        void ExecuteCallback(RegiXClient.ServiceReference1.ResultWrapper request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://egov.bg/RegiX/IRegiXEntryPointV2/ExecuteCallback", ReplyAction="http://egov.bg/RegiX/IRegiXEntryPointV2/ExecuteCallbackResponse")]
        System.Threading.Tasks.Task ExecuteCallbackAsync(RegiXClient.ServiceReference1.ResultWrapper request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://egov.bg/RegiX/SignedData")]
    public partial class RequestWrapper : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ServiceRequestData serviceRequestDataField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public ServiceRequestData ServiceRequestData {
            get {
                return this.serviceRequestDataField;
            }
            set {
                this.serviceRequestDataField = value;
                this.RaisePropertyChanged("ServiceRequestData");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://egov.bg/RegiX/SignedData")]
    public partial class ServiceRequestData : object, System.ComponentModel.INotifyPropertyChanged {
        
        private RequestProcessing requestProcessingField;
        
        private ResponseProcessing responseProcessingField;
        
        private string operationField;
        
        private System.Xml.XmlElement argumentField;
        
        private string eIDTokenField;
        
        private CallContext callContextField;
        
        private string callbackURLField;
        
        private string employeeEGNField;
        
        private string citizenEGNField;
        
        private bool signResultField;
        
        private bool returnAccessMatrixField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public RequestProcessing RequestProcessing {
            get {
                return this.requestProcessingField;
            }
            set {
                this.requestProcessingField = value;
                this.RaisePropertyChanged("RequestProcessing");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public ResponseProcessing ResponseProcessing {
            get {
                return this.responseProcessingField;
            }
            set {
                this.responseProcessingField = value;
                this.RaisePropertyChanged("ResponseProcessing");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Operation {
            get {
                return this.operationField;
            }
            set {
                this.operationField = value;
                this.RaisePropertyChanged("Operation");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public System.Xml.XmlElement Argument {
            get {
                return this.argumentField;
            }
            set {
                this.argumentField = value;
                this.RaisePropertyChanged("Argument");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public string EIDToken {
            get {
                return this.eIDTokenField;
            }
            set {
                this.eIDTokenField = value;
                this.RaisePropertyChanged("EIDToken");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public CallContext CallContext {
            get {
                return this.callContextField;
            }
            set {
                this.callContextField = value;
                this.RaisePropertyChanged("CallContext");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=6)]
        public string CallbackURL {
            get {
                return this.callbackURLField;
            }
            set {
                this.callbackURLField = value;
                this.RaisePropertyChanged("CallbackURL");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=7)]
        public string EmployeeEGN {
            get {
                return this.employeeEGNField;
            }
            set {
                this.employeeEGNField = value;
                this.RaisePropertyChanged("EmployeeEGN");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=8)]
        public string CitizenEGN {
            get {
                return this.citizenEGNField;
            }
            set {
                this.citizenEGNField = value;
                this.RaisePropertyChanged("CitizenEGN");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public bool SignResult {
            get {
                return this.signResultField;
            }
            set {
                this.signResultField = value;
                this.RaisePropertyChanged("SignResult");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public bool ReturnAccessMatrix {
            get {
                return this.returnAccessMatrixField;
            }
            set {
                this.returnAccessMatrixField = value;
                this.RaisePropertyChanged("ReturnAccessMatrix");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.FlagsAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://egov.bg/RegiX/SignedData")]
    public enum RequestProcessing {
        
        /// <remarks/>
        Verify = 1,
        
        /// <remarks/>
        Decrypt = 2,
        
        /// <remarks/>
        TransformFromPDF = 4,
        
        /// <remarks/>
        Asynchronous = 8,
    }
    
    /// <remarks/>
    [System.FlagsAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://egov.bg/RegiX/SignedData")]
    public enum ResponseProcessing {
        
        /// <remarks/>
        Encrypt = 1,
        
        /// <remarks/>
        TransformToPDF = 2,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://egov.bg/RegiX/SignedData")]
    public partial class CallContext : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string serviceURIField;
        
        private string serviceTypeField;
        
        private string employeeIdentifierField;
        
        private string employeeNamesField;
        
        private string employeeAditionalIdentifierField;
        
        private string employeePositionField;
        
        private string administrationOIdField;
        
        private string administrationNameField;
        
        private string responsiblePersonIdentifierField;
        
        private string lawReasonField;
        
        private string remarkField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string ServiceURI {
            get {
                return this.serviceURIField;
            }
            set {
                this.serviceURIField = value;
                this.RaisePropertyChanged("ServiceURI");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string ServiceType {
            get {
                return this.serviceTypeField;
            }
            set {
                this.serviceTypeField = value;
                this.RaisePropertyChanged("ServiceType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public string EmployeeIdentifier {
            get {
                return this.employeeIdentifierField;
            }
            set {
                this.employeeIdentifierField = value;
                this.RaisePropertyChanged("EmployeeIdentifier");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public string EmployeeNames {
            get {
                return this.employeeNamesField;
            }
            set {
                this.employeeNamesField = value;
                this.RaisePropertyChanged("EmployeeNames");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public string EmployeeAditionalIdentifier {
            get {
                return this.employeeAditionalIdentifierField;
            }
            set {
                this.employeeAditionalIdentifierField = value;
                this.RaisePropertyChanged("EmployeeAditionalIdentifier");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=5)]
        public string EmployeePosition {
            get {
                return this.employeePositionField;
            }
            set {
                this.employeePositionField = value;
                this.RaisePropertyChanged("EmployeePosition");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=6)]
        public string AdministrationOId {
            get {
                return this.administrationOIdField;
            }
            set {
                this.administrationOIdField = value;
                this.RaisePropertyChanged("AdministrationOId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=7)]
        public string AdministrationName {
            get {
                return this.administrationNameField;
            }
            set {
                this.administrationNameField = value;
                this.RaisePropertyChanged("AdministrationName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=8)]
        public string ResponsiblePersonIdentifier {
            get {
                return this.responsiblePersonIdentifierField;
            }
            set {
                this.responsiblePersonIdentifierField = value;
                this.RaisePropertyChanged("ResponsiblePersonIdentifier");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string LawReason {
            get {
                return this.lawReasonField;
            }
            set {
                this.lawReasonField = value;
                this.RaisePropertyChanged("LawReason");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=10)]
        public string Remark {
            get {
                return this.remarkField;
            }
            set {
                this.remarkField = value;
                this.RaisePropertyChanged("Remark");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://egov.bg/RegiX/SignedData")]
    public partial class ServiceCheckResultArgument : object, System.ComponentModel.INotifyPropertyChanged {
        
        private decimal serviceCallIDField;
        
        private string verificationCodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public decimal ServiceCallID {
            get {
                return this.serviceCallIDField;
            }
            set {
                this.serviceCallIDField = value;
                this.RaisePropertyChanged("ServiceCallID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string VerificationCode {
            get {
                return this.verificationCodeField;
            }
            set {
                this.verificationCodeField = value;
                this.RaisePropertyChanged("VerificationCode");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://egov.bg/RegiX/SignedData")]
    public partial class ServiceCheckResultWrapper : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ServiceCheckResultArgument serviceCheckResultArgumentField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public ServiceCheckResultArgument ServiceCheckResultArgument {
            get {
                return this.serviceCheckResultArgumentField;
            }
            set {
                this.serviceCheckResultArgumentField = value;
                this.RaisePropertyChanged("ServiceCheckResultArgument");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://egov.bg/RegiX/SignedData")]
    public partial class AMPropertyType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool hasAccessField;
        
        private string nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public bool HasAccess {
            get {
                return this.hasAccessField;
            }
            set {
                this.hasAccessField = value;
                this.RaisePropertyChanged("HasAccess");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://egov.bg/RegiX/SignedData")]
    public partial class AccessMatrixType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool hasAccessField;
        
        private string nameField;
        
        private AMPropertyType[] propertiesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public bool HasAccess {
            get {
                return this.hasAccessField;
            }
            set {
                this.hasAccessField = value;
                this.RaisePropertyChanged("HasAccess");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=2)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Property", IsNullable=false)]
        public AMPropertyType[] Properties {
            get {
                return this.propertiesField;
            }
            set {
                this.propertiesField = value;
                this.RaisePropertyChanged("Properties");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://egov.bg/RegiX/SignedData")]
    public partial class ResponseContainer : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Xml.XmlElement anyField;
        
        private string idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Order=0)]
        public System.Xml.XmlElement Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
                this.RaisePropertyChanged("Any");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID")]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://egov.bg/RegiX/SignedData")]
    public partial class RequestContainer : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Xml.XmlElement anyField;
        
        private string idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Order=0)]
        public System.Xml.XmlElement Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
                this.RaisePropertyChanged("Any");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID")]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://egov.bg/RegiX/SignedData")]
    public partial class DataContainer : object, System.ComponentModel.INotifyPropertyChanged {
        
        private RequestContainer requestField;
        
        private ResponseContainer responseField;
        
        private DataContainerMatrix matrixField;
        
        private string idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public RequestContainer Request {
            get {
                return this.requestField;
            }
            set {
                this.requestField = value;
                this.RaisePropertyChanged("Request");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public ResponseContainer Response {
            get {
                return this.responseField;
            }
            set {
                this.responseField = value;
                this.RaisePropertyChanged("Response");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public DataContainerMatrix Matrix {
            get {
                return this.matrixField;
            }
            set {
                this.matrixField = value;
                this.RaisePropertyChanged("Matrix");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID")]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://egov.bg/RegiX/SignedData")]
    public partial class DataContainerMatrix : AccessMatrixType {
        
        private string idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID")]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://egov.bg/RegiX/SignedData")]
    public partial class ServiceResultData : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool isReadyField;
        
        private DataContainer dataField;
        
        private System.Xml.XmlElement anyField;
        
        private bool hasErrorField;
        
        private string errorField;
        
        private decimal serviceCallIDField;
        
        private string verificationCodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public bool IsReady {
            get {
                return this.isReadyField;
            }
            set {
                this.isReadyField = value;
                this.RaisePropertyChanged("IsReady");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public DataContainer Data {
            get {
                return this.dataField;
            }
            set {
                this.dataField = value;
                this.RaisePropertyChanged("Data");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Order=2)]
        public System.Xml.XmlElement Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
                this.RaisePropertyChanged("Any");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public bool HasError {
            get {
                return this.hasErrorField;
            }
            set {
                this.hasErrorField = value;
                this.RaisePropertyChanged("HasError");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public string Error {
            get {
                return this.errorField;
            }
            set {
                this.errorField = value;
                this.RaisePropertyChanged("Error");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public decimal ServiceCallID {
            get {
                return this.serviceCallIDField;
            }
            set {
                this.serviceCallIDField = value;
                this.RaisePropertyChanged("ServiceCallID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string VerificationCode {
            get {
                return this.verificationCodeField;
            }
            set {
                this.verificationCodeField = value;
                this.RaisePropertyChanged("VerificationCode");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://egov.bg/RegiX/SignedData")]
    public partial class ResultWrapper : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ServiceResultData serviceResultDataField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public ServiceResultData ServiceResultData {
            get {
                return this.serviceResultDataField;
            }
            set {
                this.serviceResultDataField = value;
                this.RaisePropertyChanged("ServiceResultData");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IRegiXEntryPointV2Channel : RegiXClient.ServiceReference1.IRegiXEntryPointV2, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RegiXEntryPointV2Client : System.ServiceModel.ClientBase<RegiXClient.ServiceReference1.IRegiXEntryPointV2>, RegiXClient.ServiceReference1.IRegiXEntryPointV2 {
        
        public RegiXEntryPointV2Client() {
        }
        
        public RegiXEntryPointV2Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RegiXEntryPointV2Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RegiXEntryPointV2Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RegiXEntryPointV2Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public RegiXClient.ServiceReference1.ResultWrapper Execute(RegiXClient.ServiceReference1.RequestWrapper request) {
            return base.Channel.Execute(request);
        }
        
        public System.Threading.Tasks.Task<RegiXClient.ServiceReference1.ResultWrapper> ExecuteAsync(RegiXClient.ServiceReference1.RequestWrapper request) {
            return base.Channel.ExecuteAsync(request);
        }
        
        public RegiXClient.ServiceReference1.ResultWrapper CheckResult(RegiXClient.ServiceReference1.ServiceCheckResultWrapper argument) {
            return base.Channel.CheckResult(argument);
        }
        
        public System.Threading.Tasks.Task<RegiXClient.ServiceReference1.ResultWrapper> CheckResultAsync(RegiXClient.ServiceReference1.ServiceCheckResultWrapper argument) {
            return base.Channel.CheckResultAsync(argument);
        }
        
        public void AcknowledgeResultReceived(RegiXClient.ServiceReference1.ServiceCheckResultWrapper argument) {
            base.Channel.AcknowledgeResultReceived(argument);
        }
        
        public System.Threading.Tasks.Task AcknowledgeResultReceivedAsync(RegiXClient.ServiceReference1.ServiceCheckResultWrapper argument) {
            return base.Channel.AcknowledgeResultReceivedAsync(argument);
        }
        
        public void ExecuteCallback(RegiXClient.ServiceReference1.ResultWrapper request) {
            base.Channel.ExecuteCallback(request);
        }
        
        public System.Threading.Tasks.Task ExecuteCallbackAsync(RegiXClient.ServiceReference1.ResultWrapper request) {
            return base.Channel.ExecuteCallbackAsync(request);
        }
    }
}
